import { NextResponse } from 'next/server';
import { supabaseServer } from '@/lib/supabase-server';

export async function GET() {
  const { data, error } = await supabaseServer
    .from('daily_signed_reports')
    .select(`
      *,
      projects (name)
    `)
    .order('created_at', { ascending: false });

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  // Format data to match frontend requirements
  const formattedData = data.map((report: any) => ({
    id: report.id,
    projectName: report.projects?.name || 'Unknown Project',
    date: report.signed_at || report.created_at,
    timestamp: new Date(report.created_at).toLocaleString(),
    weather: {
      high: 75,
      low: 60,
      condition: 'sunny'
    },
    photos: report.signature_url ? [report.signature_url] : [],
    delays: 0
  }));

  // If no reports exist, we return a fallback mock array so the UI isn't empty 
  // until actual daily signed reports are generated by the app.
  if (formattedData.length === 0) {
    return NextResponse.json([
      {
        id: '1',
        projectName: 'Solar Artifact Site',
        date: '2026-03-25',
        timestamp: '1:43 AM | 2026-03-26 for 2026-03-25',
        weather: { high: 45, low: 58, condition: 'rainy' },
        photos: ['https://images.unsplash.com/photo-1699625809637-31c6f327ac96?w=200&h=200&fit=crop'],
        delays: 0
      },
      {
        id: '2',
        projectName: 'Big Water Wicking Project',
        date: '2026-03-25',
        timestamp: '11:00 PM | 2026-03-25 for 2026-03-25',
        weather: { high: 47, low: 76, condition: 'rainy' },
        photos: ['https://images.unsplash.com/photo-1637531347055-4fa8aa80c111?w=200&h=200&fit=crop'],
        delays: 1
      }
    ]);
  }

  return NextResponse.json(formattedData);
}
